<center><b><br>UNIDAD 2 - PRACTICA Nº1<br>Eduardo Mendieta</b></center>

<hr>
<b>NUMPY</b>

In [25]:
import numpy as np

print(f'\nVersion Numpy: {np.__version__}\n')

vector = np.array([[1,20,3],[4,5,6],[5,6,7], [4,6,7], [10,6,7]])

print(f'\nVector:\n{vector}\n')
print(f'\nTipo de dato:\n{vector.dtype}\n')
print(f'\nElementos numericos categoricos:\n{np.arange(1, 10, 2)}\n')
print(f'\nMatrices de ceros:\n{np.zeros((3,1))}\n')



Version Numpy: 1.26.4


Vector:
[[ 1 20  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 4  6  7]
 [10  6  7]]


Tipo de dato:
int32


Elementos numericos categoricos:
[1 3 5 7 9]


Matrices de ceros:
[[0.]
 [0.]
 [0.]]



<hr>
<b>PANDAS</b>

In [24]:
import pandas as pd

sueldos = [200, 400, 600]
index = ['Juan', 'Maria', 'Pedro']
data = pd.Series(sueldos, index=index)

print(f'\nSerie:\n{data}\n')
print(f'\nMaria:\n{data['Maria']}\n')

# DataFrame = conjunto de Series.
fechas = ['01/02/2023', '01/03/2023', '01/04/2023', '01/05/2023']
frutas = ['Naranja', 'Platano', 'Mandarina', 'Coco']
precios = [1, 2, 3, 2]

df = pd.DataFrame({'Fechas': fechas, 'Frutas': frutas, 'Precios': precios})
print(f'\nDataFrame:\n{df}\n')



Serie:
Juan     200
Maria    400
Pedro    600
dtype: int64


Maria:
400


DataFrame:
       Fechas     Frutas  Precios
0  01/02/2023    Naranja        1
1  01/03/2023    Platano        2
2  01/04/2023  Mandarina        3
3  01/05/2023       Coco        2

